### ISSUE TITLE
Update to campaignmonitor/createsend-php@5.1.2

### ISSUE THREAD

**Issue by silverbackdan** [Intracto/CampaignMonitorBundle#2]
Would there be issues updating composer.json to campaignmonitor/createsend-php@5.1.2 ?

The version required currently has deprecated constructors which will be removed in a future version of PHP. There is a warning as of PHP 7.0
http://php.net/manual/en/migration70.deprecated.php

I'd create a PR with the simple change but I can't see any tests so I'm not sure if it'd cause breaks without spending more time investigating.

**Comment by tvlooy** [comment]
please do open one

**Comment by silverbackdan** [comment]
Cool - I have done here https://github.com/Intracto/CampaignMonitorBundle/pull/3

**Comment by silverbackdan** [comment]
PR merged and closed now, thanks.
